{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lotris.fullname" . }}
  labels:
    {{- include "lotris.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "lotris.fullname" . }}-api
                port:
                  name: http
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{ include "lotris.fullname" . }}-api
                port:
                  name: http
          - path: /openapi
            pathType: Prefix
            backend:
              service:
                name: {{ include "lotris.fullname" . }}-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lotris.fullname" . }}-web
                port:
                  name: http
{{- end }}
